### PR TITLE
EN-US Add article Move SOGO, Roundcube and iRedAdmin to subdomains with Nginx

### PR DESCRIPTION
**Pull request by AVAtarMod**
I cannot to run .update.sh, thus please update manually, dear @iredmail :
```
* Converting /home/***/iRedMail-docs/html/index.md for index page.
./convert.sh: line 274: python: command not found
...
``` 
After replace python to python3:
```
* Converting /home/grigory/Programming/iRedMail-docs/html/index.md for index page.
Traceback (most recent call last):
  File "/home/grigory/Programming/iRedMail-docs/tools/markdown2html.py", line 10, in <module>
    import commands
ModuleNotFoundError: No module named 'commands'
...
```

Sorry for my English, this is was hard a bit to write that long text.

### CODE REVIEW

**Comment by iredmail** [comment]
Dear @AVAtarMod 

Thanks for the contribution. I think it's better create a new virtual host for example to run them as sub-domain, not modifying the default `00-default-ssl.conf`.

Could you please help write a new short tutorial to share how to create a new virtual host and run them under sub-domain instead?

**Comment by AVAtarMod** [comment]
> Could you please help write a new short tutorial to share how to create a new virtual host and run them under sub-domain instead?
Yes, I can but at default host "_" /mail, /sogo, /iredadmin are will still accessible thus this variant is maybe a bad idea?

**Comment by iredmail** [comment]
> Yes, I can but at default host "_" /mail, /sogo, /iredadmin are will still accessible thus this variant is maybe a bad idea?

Just add 1 or 2 more lines in your tutorial to mention something like "if you want to disable access of /mail, /iredadmin, please modify 00-default-ssl.conf and comment ... lines".

**Comment by AVAtarMod** [comment]
Now you can check changes 🙂

**Comment by iredmail** [comment]
Thanks for the contribution, i will slightly change the content later. :)

**Comment by iredmail** [comment]
Dear @AVAtarMod 

Your contribution is now live: https://docs.iredmail.org/subdomain.web.apps.html

Note: i modified the content, hope you don't mind.

**Comment by AVAtarMod** [comment]
Thanks for the help; I'm glad that you added steps and made the text better 🙂

**Pull request merged**
