### PR TITLE
Update upgrade.debian.9-10.md

### PR DESCRIPTION
**Pull request by Trans-IP**
Some additional findings and fixes that may be useful for others

### CODE REVIEW

**Comment by iredmail** [comment]
Dear @Trans-IP 

Thank you very much for the contribution.
There's one issue in your change: with default iRedMail configuration, Nginx is configured to connect to php-fpm network address `127.0.0.1:9999`, not the socket, so we should update `/etc/php/7.3/fpm/pool.d/www.conf` instead to listen on `127.0.0.1:9999`.

```
listen = 127.0.0.1:9999
```

Then restarting php-fpm service.

It will be easier to simply copy old `/etc/php/5.x/fpm/pool.d/www.conf` to `/etc/php/7.3/fpm/pool.d/www.conf` then restart php-fpm service.

**Comment by Trans-IP** [comment]
Thanks for the feedback.  I'll need to test this and adjust my method.  Would you like me to change this in the PR or will you be able to do it?

**Comment by iredmail** [comment]
Please help change in this PR if possible. :)

**Comment by Trans-IP** [comment]
I had the chance to test the nginx modification you suggested.  It did not work for me.  

Nginx Version 1.14.2-2+deb10u4

- Reverted changes in /etc/nginx/conf-enabled/php-fpm.conf to be: 

```
upstream php_workers {
    server unix:/var/run/php-fpm.sock;}
```
 Updated /etc/php/7.3/fpm/pool.d/www.conf to match your configuration (note my previous version was PHP 7.0)
- This resulted in failure

Original values in the www.conf for each version:
- Listen in PHP7 = /var/run/php-fpm.socket
- Listen in PHP7.3 = /run/php/php7.3-fpm.sock
 
I had to put back my original changes to make it work.  This install has been upgraded many times using the process in the documentation over time and its the first time I have upgraded the OS.

**Comment by Trans-IP** [comment]
Looks like base install uses fastcgi_pass directive for the value in the site confiiguration: 

https://tecadmin.net/install-nginx-php-fpm-debian-10/

**Comment by Trans-IP** [comment]
I see your examples:

https://github.com/iredmail/iRedMail/blob/d1f5381ad4a2500e218e86351ef5dbdf8666cab9/samples/nginx/conf-available/php_fpm.conf 

I will just delete that part from the PR so it can continue

**Comment by iredmail** [comment]
Thank you very much for the contribution. :)

**Pull request merged**
